# Generated by Django 4.1.2 on 2022-12-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordmessage',
            name='timestamp',
        ),
    ]
