# Generated by Django 4.1.2 on 2022-12-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_discordmessageattachment_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkChannel',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enable_notification', models.BooleanField(default=False)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.homeworkfile')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homework_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('day_name', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=15)),
                ('label', models.CharField(max_length=2000)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.homeworkfile')),
            ],
        ),
    ]
