# Generated by Django 4.1.2 on 2022-12-31 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_homeworkfile_homeworkchannel_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                ('discord_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='homeworkfile',
            name='password',
        ),
        migrations.AddField(
            model_name='homeworkchannel',
            name='visible_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='file_id',
            field=models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, to='api.homeworkfile'),
        ),
        migrations.AlterField(
            model_name='homeworkchannel',
            name='file_id',
            field=models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, to='api.homeworkfile'),
        ),
        migrations.CreateModel(
            name='HomeworkAccessFileAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.ForeignKey(db_column='discord_id', on_delete=django.db.models.deletion.CASCADE, to='api.discordaccount')),
                ('file_id', models.ForeignKey(db_column='file_id', on_delete=django.db.models.deletion.CASCADE, to='api.homeworkfile')),
            ],
        ),
        migrations.AddField(
            model_name='homeworkfile',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.discordaccount'),
            preserve_default=False,
        ),
    ]
