# Generated by Django 4.1.2 on 2022-12-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_discordaccount_remove_homeworkfile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkaccessfileaccount',
            name='discord_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='homeworkfile',
            name='owner_id',
            field=models.IntegerField(),
        ),
    ]
