# Generated by Django 4.1.2 on 2023-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_homeworkaccessfileaccount_discord_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkchannel',
            name='visible_only',
        ),
        migrations.AddField(
            model_name='homeworkchannel',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
