# Generated by Django 4.1.2 on 2023-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_homeworkchannel_visible_only_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordaccount',
            name='discord_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='channel_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='discord_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='message_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homeworkaccessfileaccount',
            name='discord_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='homeworkchannel',
            name='channel_id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homeworkfile',
            name='owner_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
