# Generated by Django 4.1.2 on 2023-01-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_discordaccount_discord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordaccount',
            name='discord_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='channel_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='discord_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='discordmessage',
            name='message_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homeworkaccessfileaccount',
            name='discord_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='homeworkchannel',
            name='channel_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homeworkfile',
            name='owner_id',
            field=models.CharField(max_length=20),
        ),
    ]
