# Generated by Django 4.1.2 on 2023-05-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_discordaccount_discord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homework',
            name='no_deadline',
            field=models.BooleanField(default=False),
        ),
    ]
